{{ if .Values.edge }}
kind: Service
apiVersion: v1
metadata:
  name: ant-media-server-edge
spec:
  selector:
    app: ant-media-edge
  ports:
    - name: http
      protocol: TCP
      port: 5080 
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ant-media-server-edge
spec:
  selector:
    matchLabels:
      app: ant-media-edge
  replicas: 1
  template:
    metadata:
      labels:
        app: ant-media-edge
    spec:
      {{ if .Values.hostNetwork }}
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - ant-media-edge
                - ant-media-origin
            topologyKey: "kubernetes.io/hostname"
        {{- if .Values.OriginNodeSelector }}
        {{- with .Values.affinityNode }}
        {{ toYaml . | nindent 8 }}{{- end }}
        {{ "values:" | indent 8 }}
        {{ "-" | indent 8  }}{{ .Values.OriginNodeSelector | indent 1 }}{{- end }}
      hostNetwork: {{ .Values.hostNetwork }}
      {{end}}
      dnsPolicy: ClusterFirstWithHostNet
      containers:
      - name: ant-media-server
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}" 
        imagePullPolicy: {{ .Values.image.pullPolicy }}        
        args: ["-g", "{{ .Values.UseGlobalIP }}", "-s", "{{ .Values.UseServerName }}", "-r", "{{ .Values.ReplaceCandidateAddress }}", "-m", "cluster", "-h", "{{ .Values.mongoDB }}", "-l", "{{ .Values.licenseKey }}", "-a", "{{ .Values.TurnStunServerURL }}", "-n", "{{ .Values.TurnUsername }}", "-w", "{{ .Values.TurnPassword }}", "-k", "{{ .Values.kafkaURL }}"]
        {{- if .Values.EdgeCpu }}
        livenessProbe:
          httpGet:
            path: / 
            port: 5080
          initialDelaySeconds: 30
          periodSeconds: 10
        resources:
        {{ "requests:" | indent 2 }}
        {{ "cpu:" | indent 4 }} {{ .Values.EdgeCpu }}
        {{- end }}

{{end}}
