kind: Service
apiVersion: v1
metadata:
  name: ant-media-server-origin
spec:
  selector:
    app: ant-media-origin
  ports:
    - name: http
      protocol: TCP
      port: 5080 
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ant-media-server-origin
spec:
  selector:
    matchLabels:
      app: ant-media-origin
  replicas: 1
  template:
    metadata:
      labels:
        app: ant-media-origin
    spec:
      {{ if .Values.hostNetwork }}
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - ant-media
            topologyKey: "kubernetes.io/hostname"
      hostNetwork: {{ .Values.hostNetwork }}
      {{end}}
      dnsPolicy: ClusterFirstWithHostNet
      containers:
      - name: ant-media-server
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}" 
        imagePullPolicy: {{ .Values.image.pullPolicy }}   
        args: ["-g", "true", "-s", "true", "-r", "true", "-m", "cluster", "-h", "{{ .Values.mongoDB }}", "-l", "{{ .Values.licenseKey }}"]
#        resources:
#          requests:
#             cpu: {{ .Values.resources.requests.cpu }}
