name: Ant Media Server Release

on:
  push:
    branches: [ "master" ]
    paths-ignore:
      - '**/README.md'
      - '**/.github/**'
      - '**/package.sh'
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write 

jobs:
  test_repo:
    runs-on: ubuntu-latest  
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Set up Minikube
        run: |
          sudo apt-get update
          sudo apt-get install -y conntrack
          curl -LO https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64
          sudo install minikube-linux-amd64 /usr/local/bin/minikube

      - name: Start Minikube
        run: minikube start --driver=docker

      - name: Install Helm
        run: |
          curl https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3 | bash

      - name: Install dependencies
        run: |
          helm dependency update .  

      - name: Lint Helm chart
        run: |
          helm lint .  

      - name: Deploy Helm chart to Minikube
        run: |
          helm repo add antmedia https://ant-media.github.io/helm
          helm repo update
          helm search repo
          helm install antmedia antmedia/antmedia --set origin=origin.antmedia.cloud --set edge=edge.antmedia.cloud 

      - name: Uninstall Helm release
        run: |
          helm uninstall antmedia  

      - name: Stop Minikube
        run: minikube stop
  release:
      needs: test_repo
      runs-on: ubuntu-latest  
      steps:
        - name: Checkout code
          uses: actions/checkout@v3
        - name: Get version
          id: version
          run: echo "version=$(cat VERSION)" >> $GITHUB_OUTPUT       
        - uses: "marvinpinto/action-automatic-releases@latest"
          with:
            repo_token: "${{ secrets.GITHUB_TOKEN }}"
            if: steps.version.outputs.released == 'true
            automatic_release_tag: ${{ steps.version.outputs.version }}
            prerelease: false
            files: |
              antmedia-${{ steps.version.outputs.version }}.tgz
